global:
  resolve_timeout: 5m

route:
  receiver: poc-local-demo
  group_by:
    - alertname
    - service_namespace
  group_wait: 15s
  group_interval: 1m
  repeat_interval: 4h

receivers:
  - name: poc-local-demo
