http:
  routers:
    poc-nginx-web:
      rule: Host(`localhost`) || Host(`poc.localhost`) || Host(`traefik`)
      entryPoints:
        - web
      service: poc-nginx
    poc-nginx-websecure:
      rule: Host(`localhost`) || Host(`poc.localhost`) || Host(`traefik`)
      entryPoints:
        - websecure
      service: poc-nginx
      tls: {}

  services:
    poc-nginx:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://nginx:8080
