global:
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":8080"
  websecure:
    address: ":8443"
  metrics:
    address: ":9100"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

api:
  dashboard: false

ping:
  entryPoint: metrics

log:
  level: INFO
  format: json

accessLog:
  format: json

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
